// Maps each club ID to its local badge path in /public/badges/
// Badges are SVG files served as static assets by Next.js

export const CLUB_LOGOS: Record<string, string> = {
  // EPL (20)
  mancity: "/badges/mancity.svg",
  arsenal: "/badges/arsenal.svg",
  liverpool: "/badges/liverpool.svg",
  chelsea: "/badges/chelsea.svg",
  manunited: "/badges/manunited.svg",
  tottenham: "/badges/tottenham.svg",
  newcastle: "/badges/newcastle.svg",
  astonvilla: "/badges/astonvilla.svg",
  westham: "/badges/westham.svg",
  brighton: "/badges/brighton.svg",
  crystalpalace: "/badges/crystalpalace.svg",
  fulham: "/badges/fulham.svg",
  bournemouth: "/badges/bournemouth.svg",
  brentford: "/badges/brentford.svg",
  everton: "/badges/everton.svg",
  wolves: "/badges/wolves.svg",
  nottingham: "/badges/nottingham.svg",
  leicester: "/badges/leicester.svg",
  ipswich: "/badges/ipswich.svg",
  southampton: "/badges/southampton.svg",

  // La Liga (20)
  realmadrid: "/badges/realmadrid.svg",
  barcelona: "/badges/barcelona.svg",
  atletico: "/badges/atletico.svg",
  real_sociedad: "/badges/real_sociedad.svg",
  athletic_bilbao: "/badges/athletic_bilbao.svg",
  girona: "/badges/girona.svg",
  betis: "/badges/betis.svg",
  villarreal: "/badges/villarreal.svg",
  sevilla: "/badges/sevilla.svg",
  valencia: "/badges/valencia.svg",
  osasuna: "/badges/osasuna.svg",
  getafe: "/badges/getafe.svg",
  celta: "/badges/celta.svg",
  mallorca: "/badges/mallorca.svg",
  rayo: "/badges/rayo.svg",
  laspalmas: "/badges/laspalmas.svg",
  alaves: "/badges/alaves.svg",
  leganes: "/badges/leganes.svg",
  valladolid: "/badges/valladolid.svg",
  espanyol: "/badges/espanyol.svg",

  // Serie A (20)
  inter: "/badges/inter.svg",
  juventus: "/badges/juventus.svg",
  milan: "/badges/milan.svg",
  napoli: "/badges/napoli.svg",
  atalanta: "/badges/atalanta.svg",
  roma: "/badges/roma.svg",
  lazio: "/badges/lazio.svg",
  fiorentina: "/badges/fiorentina.svg",
  bologna: "/badges/bologna.svg",
  torino: "/badges/torino.svg",
  monza: "/badges/monza.svg",
  genoa: "/badges/genoa.svg",
  lecce: "/badges/lecce.svg",
  udinese: "/badges/udinese.svg",
  verona: "/badges/verona.svg",
  empoli: "/badges/empoli.svg",
  cagliari: "/badges/cagliari.svg",
  parma: "/badges/parma.svg",
  como: "/badges/como.svg",
  venezia: "/badges/venezia.svg",

  // Bundesliga (18)
  bayern: "/badges/bayern.svg",
  leverkusen: "/badges/leverkusen.svg",
  dortmund: "/badges/dortmund.svg",
  leipzig: "/badges/leipzig.svg",
  stuttgart: "/badges/stuttgart.svg",
  frankfurt: "/badges/frankfurt.svg",
  freiburg: "/badges/freiburg.svg",
  hoffenheim: "/badges/hoffenheim.svg",
  heidenheim: "/badges/heidenheim.svg",
  werder: "/badges/werder.svg",
  wolfsburg: "/badges/wolfsburg.svg",
  monchengladbach: "/badges/monchengladbach.svg",
  union_berlin: "/badges/union_berlin.svg",
  mainz: "/badges/mainz.svg",
  bochum: "/badges/bochum.svg",
  stpauli: "/badges/stpauli.svg",
  kiel: "/badges/kiel.svg",
  augsburg: "/badges/augsburg.svg",

  // Ligue 1 (18)
  psg: "/badges/psg.svg",
  monaco: "/badges/monaco.svg",
  marseille: "/badges/marseille.svg",
  lille: "/badges/lille.svg",
  lens: "/badges/lens.svg",
  lyon: "/badges/lyon.svg",
  nice: "/badges/nice.svg",
  rennes: "/badges/rennes.svg",
  reims: "/badges/reims.svg",
  brest: "/badges/brest.svg",
  strasbourg: "/badges/strasbourg.svg",
  toulouse: "/badges/toulouse.svg",
  montpellier: "/badges/montpellier.svg",
  nantes: "/badges/nantes.svg",
  angers: "/badges/angers.svg",
  saint_etienne: "/badges/saint_etienne.svg",
  le_havre: "/badges/le_havre.svg",
  auxerre: "/badges/auxerre.svg",
};
