import { NextRequest, NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

export async function POST(req: NextRequest) {
  try {
    const { firstName, lastName, nationality, age, playingStyle } = await req.json();

    const prompt = `A highly detailed, photorealistic headshot portrait of a football manager named ${firstName} ${lastName}. 
    They are ${nationality}, ${age} years old, dressed in a sharp modern manager suit. 
    They have a serious, intense expression that reflects their ${playingStyle} tactical style.
    The background should be a subtle stadium blur or locker room. Professional photography, cinematic lighting, 8k resolution.`;

    const response = await ai.models.generateImages({
      model: "imagen-3.0-generate-001",
      prompt: prompt,
      config: {
        numberOfImages: 1,
        outputMimeType: "image/jpeg",
        aspectRatio: "1:1"
      }
    });

    if (!response.generatedImages || response.generatedImages.length === 0 || !response.generatedImages[0].image) {
      throw new Error("No image generated by Imagen model.");
    }

    const base64Image = response.generatedImages[0].image.imageBytes;

    return NextResponse.json({
      success: true,
      image: `data:image/jpeg;base64,${base64Image}`
    });
  } catch (error: any) {
    console.error("AI Face Generation Error:", error);
    return NextResponse.json(
      { success: false, error: "Failed to generate AI face profile", details: error.message },
      { status: 500 }
    );
  }
}
